alt_color_list = c("Akron",
                   "Baylor",
                   "Charlotte",
                   "Houston",
                   "Iowa",
                   "Kent State",
                   "LSU",
                   "Maryland",
                   "Minnesota",
                   "Montana",
                   "NC State",
                   "North Texas",
                   "Northwestern",
                   "SMU",
                   "Temple",
                   "Tennessee",
                   "Tulsa",
                   "UC Davis",
                   "UCLA",
                   "UMass",
                   "USC",
                   "Utah State",
                   "Wisconsin",
                   "Ohio State",
                   "Purdue")

alt_logo_list = c("Air Force",
                  "Alabama",
                  "Boston College",
                  "BYU",
                  "California",
                  "Cincinnati",
                  "Clemson",
                  "Duke",
                  "Indiana",
                  "James Madison",
                  "Kansas State",
                  "Kentucky",
                  "LSU",
                  "Michigan",
                  "Michigan State",
                  "Nevada",
                  'Oklahoma',
                  "Oregon",
                  "Pittsburgh",
                  "Rice",
                  "San Diego State",
                  "TCU",
                  "Texas",
                  "Texas A&M",
                  "Wake Forest",
                  "Washington State")
